# Generated by Django 3.1 on 2020-10-11 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintname', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'newcomplaints',
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinesname', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'newmedicines',
            },
        ),
        migrations.CreateModel(
            name='PatientCheckUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmpdob', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=500, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True)),
                ('generalcondition', models.CharField(max_length=50)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=110, null=True)),
                ('pulse', models.IntegerField()),
                ('systolicpressure', models.IntegerField()),
                ('dystolicpressure', models.IntegerField()),
                ('respiratoryrate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('checkupremake', models.CharField(blank=True, max_length=250, null=True)),
                ('respiratorysystem', models.CharField(blank=True, max_length=50, null=True)),
                ('cardiovascularsystem', models.CharField(blank=True, max_length=50, null=True)),
                ('centralnervoussystem', models.CharField(blank=True, max_length=50, null=True)),
                ('palpitation1', models.CharField(blank=True, max_length=20, null=True)),
                ('palpitation2', models.CharField(blank=True, max_length=20, null=True)),
                ('palpitation3', models.TextField()),
                ('provisionaldiagnosis', models.CharField(blank=True, max_length=20, null=True)),
                ('followup', models.CharField(blank=True, max_length=200, null=True)),
                ('filed_date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientcheckup_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientcheckup_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('time1', models.CharField(max_length=10)),
                ('when1', models.CharField(max_length=10)),
                ('numberofdays1', models.IntegerField()),
                ('name2', models.CharField(max_length=200)),
                ('time2', models.CharField(max_length=10)),
                ('when2', models.CharField(max_length=10)),
                ('numberofdays2', models.IntegerField()),
                ('name3', models.CharField(max_length=200)),
                ('time3', models.CharField(max_length=10)),
                ('when3', models.CharField(max_length=10)),
                ('numberofdays3', models.IntegerField()),
                ('name4', models.CharField(max_length=200)),
                ('time4', models.CharField(max_length=10)),
                ('when4', models.CharField(max_length=10)),
                ('numberofdays4', models.IntegerField()),
                ('specialinstruction', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patientcheckup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcheckup')),
            ],
        ),
        migrations.CreateModel(
            name='PatientComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint1', models.CharField(blank=True, max_length=50, null=True)),
                ('since1', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint2', models.CharField(blank=True, max_length=50, null=True)),
                ('since2', models.CharField(blank=True, max_length=20, null=True)),
                ('complaint3', models.CharField(blank=True, max_length=50, null=True)),
                ('since3', models.CharField(blank=True, max_length=20, null=True)),
                ('patientcheckup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientcheckup')),
            ],
        ),
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('paid_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_patient', to=settings.AUTH_USER_MODEL)),
                ('patientcomplaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_patientcomplaint', to='home.patientcomplaint')),
            ],
        ),
    ]
