# Generated by Django 3.1 on 2020-09-20 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20200920_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('paid_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_patient', to=settings.AUTH_USER_MODEL)),
                ('patientcomplaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_patientcomplaint', to='home.patientcomplaint')),
            ],
        ),
    ]
